

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile

    image: support
    container_name: support_api
    ports:
      - '8000:8000'
    env_file: '.env'
    depends_on:
      - database

  database:
    image: 'postgres:16'
    container_name: support_database
    env_file: '.env'
    ports:
      - '5432:5432'
