# Generated by Django 4.2.11 on 2024-05-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0002_issue_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["id"], "verbose_name": "Issue"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="issue",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="senior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="senior_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Opened"), (2, "In progress"), (3, "Closed")]
            ),
        ),
    ]
