name: Check code quality

on: [push]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install black ruff isort mypy pydantic[mypy] httpx django django-stubs
      - name: Run formatters
        run: python -m black --check . && python -m isort --check .
      - name: Run linter
        run: python -m ruff .
      - name: Run static type checker
        run: python -m mypy .
